### ISSUE TITLE
LUA转表问题

### ISSUE THREAD

**Issue by an7728777** [davyxu/tabtoy#10]
xlsx转lua文件时，.lua文件中，数据的枚举值对应的值是@Type中的FieldName字段名(是一个string)，不是Value里面的枚举值(int)。手动在lua.go文件 的16行`return fmt.Sprintf("%v", n.Value)`改成`return fmt.Sprintf("%v", n.EnumValue)`，取到了枚举值里面的Value值，暂时解决了需求。如果lua想去枚举类型的Value值，直接改这个的话，不知道有没有问题？

**Comment by davyxu** [comment]
枚举没有用整形而直接用字符串的考虑是因为: lua本身就没有枚举类型. lua在使用40个字符以下的字符串的效率和整形是一致的, 底层做过字符串驻留处理

lua的底层对一个lua文件的local数量限制在200个, 生成local方式的模拟枚举类型的后果就是编译不过
不过, 我会添加一个在枚举字符串与值之间互转的函数, 看是否方便?

**Comment by w1ng** [comment]
更新到最新版本,导出配置到lua之后
`tab.Enum`这个枚举表变成个空表了....
