### ISSUE TITLE
直链github使用go get 报错

### ISSUE THREAD

**Issue by HarryWang29** [davyxu/tabtoy#114]
执行 `go get github.com/davyxu/tabtoy`

----------------------

如果是直链github不使用goproxy的话，报错
```
go: github.com/davyxu/tabtoy@v0.0.0-20220828125452-4247c6f924e5 requires
        github.com/tealeg/xlsx@v1.0.4-0.20190601071628-e2d23f3c43dc: invalid pseudo-version: revision e2d23f3c43dc is not a descendent of preceding tag (v1.0.3)
```
经过查看`github.com/tealeg/xlsx`的tag信息，发现`v1.0.4`已被删除，建议修改使用版本

--------------------

使用`GOPROXY=https://goproxy.cn,direct;`，可正常引用

**Comment by davyxu** [comment]
一般情况都是直接用代理的吧. 

github.com/tealeg/xlsx官方怎么可以随便删tag...

**Comment by HarryWang29** [comment]
我默认是不使用代理的，关于tag，你可以去看下啊，v1.0.3后面就是v1.0.5了，就没v1.0.4

**Comment by davyxu** [comment]
稍后会考虑升级, 但兼容性是个大问题
如果还是不考虑代理, 就把github.com/tealeg/xlsx取一份喜欢的版本放到本地做go mod replace再编译就可以了

**Comment by davyxu** [comment]
更新提上来了,只升小版本
