### ISSUE TITLE
竖行的表格，repeated type 有点问题

### ISSUE THREAD

**Issue by ronow2cn** [davyxu/tabtoy#16]
竖行的表格，如果有两行都是repeated 类型。而且值填的是多项会报错。但是两个都填一项正常。
例如：Item 在globals.xlsx定义
字段名	        类型	                特性	                 注释	        值
InitMaterial	repeated Item	ListSpliter: ";"	 初始材料	类型:材料 id:4005 数量:1	
InitGoods	repeated Item	ListSpliter: ";"	 初始材料	类型:材料 id:4005 数量:1	
上面正常；
字段名	        类型	                特性	                 注释	        值
InitMaterial	repeated Item	ListSpliter: ";"	 初始材料	类型:材料 id:4005 数量:1;  类型:材料 id:4006 数量:1	
InitGoods	repeated Item	ListSpliter: ";"	 初始材料	类型:材料 id:4005 数量:1
这个报错：“数据表: 单元格转换错误, name: 'InitMaterials' repeated type: 'Item' raw: '类型:材料 id:4005 数量:1;'”

**Comment by davyxu** [comment]
多少版本?
