### ISSUE TITLE
可以让生成的lua配置支持枚举是数字吗？

### ISSUE THREAD

**Issue by wushi333333** [davyxu/tabtoy#19]

**Comment by davyxu** [comment]
导出参数中添加 --luaenumintvalue=true

**Comment by wushi333333** [comment]
好的，谢谢了

**Comment by wushi333333** [comment]
<code>..\tabtoy.exe ^
--luaenumintvalue=true ^
--mode=exportorv2 ^
--lua_out=.\Config.lua ^
--json_out=.\Config.json ^
--lan=zh_cn ^
Globals.xlsx ^</code>

是这样的吗？不得行啊

**Comment by davyxu** [comment]
报什么错？

**Comment by wushi333333** [comment]
but not defined: -luaenumintvalue
是不是我版本老了？

**Comment by davyxu** [comment]
链接：http://pan.baidu.com/s/1o7AkSII 密码：iq1z
用这个新版

**Comment by wushi333333** [comment]
好的，谢谢了
