### ISSUE TITLE
倒出的文件比xlsx大2倍

### ISSUE THREAD

**Issue by yingnierxiao** [davyxu/tabtoy#24]
在字段上面可以在优化下，比如256以内的数值可以在压缩

**Comment by davyxu** [comment]
二进制还是json?

**Comment by yingnierxiao** [comment]
二进制的文件
drwxr-xr-x   9 zj  staff      306  2  7 14:51 .
drwx------+ 31 zj  staff     1054  2  7 14:21 ..
-rw-r--r--   1 zj  staff     9380  2  7 14:58 Config.cs
-rw-r--r--   1 zj  staff  1595846  2  7 14:58 Config.dat
-rw-r--r--@  1 zj  staff    13180  2  7 14:51 Globals.xlsx
-rw-r--r--   1 zj  staff      145  2  7 14:31 convert.sh
-rw-------@  1 zj  staff   625914  2  7 14:58 s_skill_battle.xlsx

**Comment by davyxu** [comment]
xlsx本身就是zip压缩过的,二进制输出默认不压缩.  
如果使用zigzag也只能压缩整数,而且这会让加载代码更加复杂,影响加载效率
所以最好的方法是在文件上压缩下较好

**Comment by yingnierxiao** [comment]
s_skill_battle.csv 798054的大小也比较小  说还是有比较大的空间可以压缩的

**Comment by davyxu** [comment]
和csv比没意义, 二进制格式以后会扩展到不同的语言,增加复杂度很麻烦. 你看xlsx也没有做整数优化啊,文本保存的,一口气zip压缩就好了

**Comment by yingnierxiao** [comment]
主要是有些字段可能用不到int32   只要int8 或者int16就足够了

**Comment by davyxu** [comment]
你的意思是增加int8和int16嘛,这个可以
