### ISSUE TITLE
单结构解析的显示问题 策划表示|比较好看点  目前只能用空格

### ISSUE THREAD

**Issue by yingnierxiao** [davyxu/tabtoy#26]
SingleStruct
--
Prop
 
单结构解析
血量:100  攻击速率:1.2

比如这样  血量:100|攻击速率:1.2

**Comment by davyxu** [comment]
传统的解析法都是字符串切割, 这个我用的是词法器,添加起来非常麻烦,而且不一定语义正确

让策划习惯下吧

**Comment by yingnierxiao** [comment]
好吧目前看来没什么其他问题，就是配置策划要重新配置下，导出走ci。good job
