### ISSUE TITLE
Globals的类型能支持独立导出c#文件吗？

### ISSUE THREAD

**Issue by yingnierxiao** [davyxu/tabtoy#28]
Globals的类型能支持独立导出c#文件吗？分表打包的时候共享类型会重复

**Comment by davyxu** [comment]
-type_out=xxxx.json
可以导出所有类型

**Comment by yingnierxiao** [comment]
不是这个意思。比Globals.xlsx  ver3     map.xlsx 也有字段    map_npc.xlsx也有这个字段，但是想把数据分开来导出，cs的代码也要分开来，map.cs 和map_npc.cs就会同时有ver3的class出来就会编译报错了

**Comment by davyxu** [comment]
Global里放一份就好了嘛，把Global放在命令行的第一位导出，后面会依赖Global的类型

**Comment by yingnierxiao** [comment]
导出的代码会出现每个.cs都有ver3的class类型  编译的时候就会提示重复了

**Comment by davyxu** [comment]
重复利用的类型，在Global放一份就可以了

**Comment by davyxu** [comment]
所有电子表格一次导出，不要一个表导一次

**Comment by yingnierxiao** [comment]
所有文件一下导出导出的数据包会很大.所以想分开来导出

**Comment by VergilGao** [comment]
这里也有同样的需求，在配置关卡时希望能每个关卡都生成属于自己的数据包。
