### ISSUE TITLE
  提个建议，在生成的C#代码中加入接口

### ISSUE THREAD

**Issue by VergilGao** [davyxu/tabtoy#30]
v2版本生成的C#代码，要想读取数据一般都是引用tabtoy.xxxTable.Config，而在写读取代码时，因为没有接口，只能针对不同的数据表写不同的代码，但是其中许多代码都是重复的。
我观察了一下，实际上在写读取类时，可以写这样的代码来做到通用的读取：
TabtoyHelper.DataReader<DataConfig, DataDefine>();
那么完全可以让前文所述的类型继承ITabtoyConfig接口，而数据xxxDefine类型则继承一个空接口ITabtoyDataDefine接口。
这样用户在写读取方法时就可以这样写：
TDefine[] TabtoyHelper.DataReader<TConfig,TDefine>() where TConfig : ITabtoyConfig, TDefine : ITabtoyDataDefine{
...
}

**Comment by VergilGao** [comment]
不好意思我之前没写清楚思路，这里有一个按照我思路大概写出来的一个读表类，可以做到对所有的表都可以直接读取，而不需要重复写读表这个过程：
`using tabtoy;

public class TabtoyHelper<TConfig, TDefine> where TConfig : ITabToyConfig, TDefine : IDefine {

    public TConfig DataReader (string filePath) {
        using (var stream = new FileStream (filePath, FileMode.Open)) {
            stream.Position = 0;

            var reader = new DataReader (stream);

            if (!reader.ReadHeader ()) {
                Console.WriteLine ("combine file crack!");
                return;
            }

            var config = new TConfig ();
            table.Config.Deserialize (config, reader);

            return config;
        }
    }
}`

**Comment by davyxu** [comment]
你是想把每个结构单独读取吧？

**Comment by VergilGao** [comment]
不是，假如我有5个不同的表，Player， Item， Map 。。。
我通过上面写的方法就可以做到一套代码复用给这5个表的读取，至于读取完数据怎么用，再分别写各自的代码。
因为我发现上面的代码我每处理一个新的表，都要复制改写一次。

**Comment by davyxu** [comment]
你不是直接用表数据，而是拷贝一份吧？

**Comment by VergilGao** [comment]
对的，我这里就是把表数据缓存下来了，然后按需使用。
如果我把TabtoyHelper做成单例类的话，也可以通过Clear方法清理缓存。
总的来说，就是对数据的使用更自由了。

**Comment by davyxu** [comment]
这种并不是tabtoy建议的用法，两份数据你维护起来会很麻烦。

**Comment by VergilGao** [comment]
我没有两份数据啊，只有一份数据。

**Comment by Wecica** [comment]
> 不好意思我之前没写清楚思路，这里有一个按照我思路大概写出来的一个读表类，可以做到对所有的表都可以直接读取，而不需要重复写读表这个过程：
> 
> ```
> using tabtoy;
> 
> public class TabtoyHelper<TConfig, TDefine> where TConfig : ITabToyConfig, TDefine : IDefine {
> 
>     public TConfig DataReader (string filePath) {
>         using (var stream = new FileStream (filePath, FileMode.Open)) {
>             stream.Position = 0;
> 
>             var reader = new DataReader (stream);
> 
>             if (!reader.ReadHeader ()) {
>                 Console.WriteLine ("combine file crack!");
>                 return;
>             }
> 
>             var config = new TConfig ();
>             TConfig.Deserialize (config, reader);
> 
>             return config;
>         }
>     }
> }
> ```
> 
> 这个类可以由使用者自己来写，根据他们的需要用DI或者单例等方式来写这个TabtoyHelper
> 
> 要实现这样的写法只需要在生成的C#文件中，Config类继承一个ITabToyConfig的空接口，PlayerDefine类继承一个IDefine的空接口。同时在原本tabtoy的C#代码中加入上述两个空接口的定义即可。

你这里TConfig.Deserialize(config, reader)不能直接调用吧，你这么解决这里的问题的？
