### ISSUE TITLE
支持公式么？

### ISSUE THREAD

**Issue by chiuan** [davyxu/tabtoy#33]
请问支持excel的公式么？

**Comment by davyxu** [comment]
不支持

**Comment by chiuan** [comment]
> 不支持

请问会计划支持么??

**Comment by davyxu** [comment]
没有支持的意义啊，提前用excel算法导出值不是更好？何必在运行期计算

**Comment by chiuan** [comment]
> 没有支持的意义啊，提前用excel算法导出值不是更好？何必在运行期计算

oh no...

例如一些计算。可以策划设计好一个公式（即接口）
例如我们写一个计算英雄属性的战斗力吧func(hp,mp,atk,def,...){}
其实具体里面怎么算的。程序员不需要care。。策划自己幻想自己改。程序要做的就是看你接口传参数获得结果即可。

**Comment by davyxu** [comment]
这是你该做的，不是导表工具做的事情
https://github.com/davyxu/tabtoy/tree/master/v2/exprvm
这里有个简单的虚拟机，实在想要，可以参考这里的代码

**Comment by chiuan** [comment]
> 这是你该做的，不是导表工具做的事情
> https://github.com/davyxu/tabtoy/tree/master/v2/exprvm
> 这里有个简单的虚拟机，实在想要，可以参考这里的代码

https://github.com/supermobs/SuperConfig
我们有实现了. 探讨一下.还挺方便的.最近在写导出typescript

有个问题我想看下别人是怎样解决config太多数据时候的加载的.

**Comment by davyxu** [comment]
都开源的,你可以fork一份自己加.但这种需求不是每个人都有,我不会在我的tabtoy里加入这种小众需求的
