### ISSUE TITLE
Windows only?

### ISSUE THREAD

**Issue by webloverand** [davyxu/tabtoy#34]

**Comment by davyxu** [comment]
windows外的平台自己编译

**Comment by webloverand** [comment]
你好,我下载了源代码,并进入该路径,在终端使用go build进行编译
编译的时候出现如下问题 :
main.go:6:2: cannot find package "github.com/davyxu/golog" in any of:
	/usr/local/go/src/github.com/davyxu/golog (from $GOROOT)
	/Users/icey/go/src/github.com/davyxu/golog (from $GOPATH)
entry_v2.go:5:2: cannot find package "github.com/davyxu/tabtoy/v2" in any of:
	/usr/local/go/src/github.com/davyxu/tabtoy/v2 (from $GOROOT)
	/Users/icey/go/src/github.com/davyxu/tabtoy/v2 (from $GOPATH)
entry_v2.go:6:2: cannot find package "github.com/davyxu/tabtoy/v2/i18n" in any of:
	/usr/local/go/src/github.com/davyxu/tabtoy/v2/i18n (from $GOROOT)
	/Users/icey/go/src/github.com/davyxu/tabtoy/v2/i18n (from $GOPATH)
entry_v2.go:7:2: cannot find package "github.com/davyxu/tabtoy/v2/printer" in any of:
	/usr/local/go/src/github.com/davyxu/tabtoy/v2/printer (from $GOROOT)
	/Users/icey/go/src/github.com/davyxu/tabtoy/v2/printer (from $GOPATH)
entry_v2tov3.go:5:2: cannot find package "github.com/davyxu/tabtoy/v2tov3" in any of:
	/usr/local/go/src/github.com/davyxu/tabtoy/v2tov3 (from $GOROOT)
	/Users/icey/go/src/github.com/davyxu/tabtoy/v2tov3 (from $GOPATH)

完全不懂Go语言,麻烦不吝赐教,非常感谢

**Comment by davyxu** [comment]
用go get 编译，不是下载zip，按照说明走
