### ISSUE TITLE
使用Go编辑命令后运行示例出现tabtoy: command not found

### ISSUE THREAD

**Issue by webloverand** [davyxu/tabtoy#35]
是按照说明进行编译的 :
go get -u -v github.com/davyxu/tabtoy

但是运行示例时出现 :
-bash: tabtoy: command not found

**Comment by davyxu** [comment]
你装golang的包没？
如果是windows， 直接在Release里下载编译好的包

**Comment by webloverand** [comment]
是MAC,装了golang
执行 go version
输出如下
go version go1.12.1 darwin/amd64

**Comment by davyxu** [comment]
没看懂你那个报错意思，编译不会去执行tabtoy本身的

**Comment by webloverand** [comment]
我是在终端运行案例报这个错误的
tabtoy --mode=v2 --json_out=config.json --combinename=Config Table.xlsx

**Comment by davyxu** [comment]
确认下路径，当前目录用./

**Comment by webloverand** [comment]
解决了.谢谢

**Comment by readpan** [comment]
虽然这issue关了, 但我想说对于不太了解编译的人来说在mac下真的一头雾水.
当使用``go get -u -v github.com/davyxu/tabtoy`` 编译后, 将得到``/Users/username/go/bin/tabtoy``
