### ISSUE TITLE
可以考虑支持导出成功失败文字颜色不同吗

### ISSUE THREAD

**Issue by yangyuzhou** [davyxu/tabtoy#36]
我们导出的时候是一个CMD控制台，上面会刷新狠多数据，全部都是黑底白字。
在有几十个表格的时候，谁导出成功谁导出失败了，看的不是很明显。
可以支持导出成功时文字显示为绿色，导出失败时文字显示为红色吗，类似于SVN的感觉？

**Comment by davyxu** [comment]
建议很好, tabtoy错误一般都是在最后一个, 只需要在bat加一个返回值探测就可以在导出错误时停止

把这个语句放在末尾
@IF %ERRORLEVEL% NEQ 0 pause

例子中有

**Comment by yangyuzhou** [comment]
收到
