### ISSUE TITLE
【建议】可以考虑支持注释掉行吗

### ISSUE THREAD

**Issue by yangyuzhou** [davyxu/tabtoy#37]
我们新来了个同学，习惯是注释掉一行
现在的#是可以注释一列
测试了下是不能注释掉行的，在int32这个pid检查的时候就报错了

//仅作建议，我不慌

**Comment by davyxu** [comment]
行注释功能在v3中支持, v2暂时不支持, 可以采用空行方式, 或者把临时数据放在单独的sheet中, sheet名字最前加一个#

v3尚在测试中, 不建议在项目中使用

**Comment by yangyuzhou** [comment]
好的 收到
