### ISSUE TITLE
请问是否有考虑支持 FlatBuffers？

### ISSUE THREAD

**Issue by aenerv7** [davyxu/tabtoy#39]
和 ProtoBuffers 师出同门的 FlatBuffers 似乎是更适合用在游戏开发领域的，它网站上的一些介绍就足够表明 FlatBuffers 的优势了：

> 网站：https://google.github.io/flatbuffers/
> Benchmark：https://google.github.io/flatbuffers/flatbuffers_benchmarks.html

请问 tabtoy 是否有支持导出 FlatBuffers 的打算呢？

**Comment by davyxu** [comment]
tabtoy 下一个版本 只支持导出json,  二进制格式需要借助第三方工具例如msgp转为msgpack格式

至于flatbuffer, 应该是可以从json转的

**Comment by aenerv7** [comment]
哦哦，也就是说下一阶段计划是只负责导出 json 格式，把其他格式的支持交给其他工具来负责？我还真没考虑过以 json 为基础生成其他格式数据的事情，我来去查一下，谢谢~

**Comment by aenerv7** [comment]
找到了相关内容，FlatBuffers 确实原生支持从 json 格式的数据 parse，方便以后有同样疑问的开发者我把相关链接贴在下面：

> FlatBuffers -> Use in C++ -> Text & schema parsing
> https://google.github.io/flatbuffers/flatbuffers_guide_use_cpp.html
