### ISSUE TITLE
关于电子表格格式

### ISSUE THREAD

**Issue by LitpoEric** [davyxu/tabtoy#4]
请问有规则可以跳过一行，跳过一列，以及跳过一行剩余的内容这种约定吗？
因为有的时候策划希望在表格上写注释
比方说某个单元格以##开头表示跳过后续内容，某列单元格的type类型没有定义表示该单元列为无效，这种逻辑

**Comment by davyxu** [comment]
现在只支持通过在字段前加#跳过列, 跳过行的需求可以被支持!
