### ISSUE TITLE
i18n包中的init函数是如何保证顺序的

### ISSUE THREAD

**Issue by woshihuo12** [davyxu/tabtoy#40]
如题，包中的源文件都包含init函数，但谁先谁后有什么注意的地方？

**Comment by davyxu** [comment]
init不保证顺序

**Comment by woshihuo12** [comment]
那其中一个默认设为英文的那个init就是多余的，或者说是不对的

**Comment by davyxu** [comment]
贴出代码来

**Comment by davyxu** [comment]
如果是不对的, 请证明. SetLanguage只有1个地方在调用, 而且有默认值

**Comment by woshihuo12** [comment]
func init() {
	SetLanguage("en_us")
}

i18n 模块中的这个init函数，字面意思难道不需要en_us的模块的init函数先行调用么。
当然可能由于e在i前面造成事实确实不会出错误。

**Comment by davyxu** [comment]
en_us和i18n在一个模块...

**Comment by woshihuo12** [comment]
但是那个模块有3个init函数
