### ISSUE TITLE
考虑支持linux吗

### ISSUE THREAD

**Issue by namelcx** [davyxu/tabtoy#41]
如题

**Comment by davyxu** [comment]
自己用go源码编译下， README里都有， 任何你能想到的平台都支持

**Comment by namelcx** [comment]
追问一下，MakeIndex创建索引对json不生效的吗？

**Comment by davyxu** [comment]
数据建索引， json如何索引？

**Comment by namelcx** [comment]
以MakeIndex那一列作为键，其余的作为一个对象。当然把JSON反序列化后也可以自建索引

**Comment by davyxu** [comment]
MakeIndex只对编程语言有作用

**Comment by namelcx** [comment]
恩，那只有decode后自己处理了
