### ISSUE TITLE
区分开前后端配置

### ISSUE THREAD

**Issue by 514366607** [davyxu/tabtoy#42]
如道具表，会有图标名的列，这个字段后端是用不到的。能不能区分前后端的配置？

**Comment by davyxu** [comment]
拆两个shell导出就好了嘛

**Comment by 514366607** [comment]
但是这样会出现很多重复的字段且容易出现人为错误。
能不能在头部加上一行。用于区分前后或共用配置的列。问过策划之前的游戏他们是这么做的，我感觉可以参考下。

**Comment by davyxu** [comment]
你可以自己fork代码改

**Comment by 514366607** [comment]
我在  v2 还是 v3下加？
