### ISSUE TITLE
为什么@Types中FieldType不能用string

### ISSUE THREAD

**Issue by chen413480505** [davyxu/tabtoy#43]
![image](https://user-images.githubusercontent.com/29225546/74225996-b45ed100-4cf6-11ea-811b-30768292744b.png)
![image](https://user-images.githubusercontent.com/29225546/74226023-bd4fa280-4cf6-11ea-8d31-777acb50676a.png)

**Comment by chen413480505** [comment]
d

**Comment by davyxu** [comment]
你仔细检查下你的表数据, 用例子参考下.  实际读到的是465

**Comment by chen413480505** [comment]
我还想请教您一下，如果@Types里声明了string类型，在DataSheet里配置的时候使用了C#占位符{0}，比如 "xxx有{0}个糖果"，导出的时候是会有类型转换错误的提示的图示：








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Davy xu"<notifications@github.com&gt;; 
发送时间: 2020年2月11日(星期二) 下午5:56
收件人: "davyxu/tabtoy"<tabtoy@noreply.github.com&gt;; 
抄送: "霸气的阿布叔叔"<413480505@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [davyxu/tabtoy] 为什么@Types中FieldType不能用string (#43)




你仔细检查下你的表数据, 用例子参考下.  实际读到的是465

**Comment by davyxu** [comment]
没碰到过类似问题

**Comment by chen413480505** [comment]
好的，感谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Davy xu"<notifications@github.com&gt;; 
发送时间: 2020年2月11日(星期二) 晚上6:06
收件人: "davyxu/tabtoy"<tabtoy@noreply.github.com&gt;; 
抄送: "霸气的阿布叔叔"<413480505@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [davyxu/tabtoy] 为什么@Types中FieldType不能用string (#43)




没碰到过类似问题
