### ISSUE TITLE
BuildID 不会改变

### ISSUE THREAD

**Issue by huangchaoqun** [davyxu/tabtoy#46]
导出两份配置二机制配表 确定导表内容不一样  导出来的c#文件的BuildID 相同

**Comment by davyxu** [comment]
请制作最小验证表格重现此问题, 从描述无法排除你本地环境影响

**Comment by huangchaoqun** [comment]
[buildIDTest.zip](https://github.com/davyxu/tabtoy/files/4626943/buildIDTest.zip)
执行脚本后会在outPut输出 然后两个C#文件里面的buildID相同

**Comment by davyxu** [comment]
BuildID保证的是类型, 而不是数据

**Comment by huangchaoqun** [comment]
我新增了表 并且packageName也不一样  这样导出来的类型还会一样？？？？

**Comment by huangchaoqun** [comment]
从百度网盘上下载最新的exe会爆

Microsoft Defender SmartScreen 阻止了无法识别的应用启动。运行此应用可能会导致你的电脑存在风险。

**Comment by huangchaoqun** [comment]
Microsoft Defender SmartScreen 阻止了无法识别的应用启动。运行此应用可能会导致你的电脑存在风险。
最新exe会提示这个

**Comment by davyxu** [comment]
开发请关闭各类杀毒软件, go二进制头本来就会被各种杀毒软件报毒
觉得不安全, 请自行编译

**Comment by huangchaoqun** [comment]
好的 谢谢拉
