### ISSUE TITLE
数据结构和 Package 名一致的情况下生成不同内容后 BuildID 不一致

### ISSUE THREAD

**Issue by aenerv7** [davyxu/tabtoy#48]
使用 2.9.3 版本会出现这个问题，我也看到了这个 issue：[Issue 46](https://github.com/davyxu/tabtoy/issues/46)，如果 BuildID 是保证类型的话，那么按说只是单纯的内容不同并不会导致 BuildID 不同。

**Comment by davyxu** [comment]
请提供最小例子,  BuildID是用生成的CS代码的hash来做的, 和数据无关

**Comment by aenerv7** [comment]
我发现有一个字段在两份表中的 "Default" 值不一致，但是类型是一样的，这样的话 BuildID 也会不一样的嘛？

**Comment by davyxu** [comment]
是的, Default值会影响, meta内容属于表类型

**Comment by aenerv7** [comment]
我又测试了一下，如果把 "Default" 改成一致的那么 BuildID 就一致了，应该就是这个原因了。
