### ISSUE TITLE
repeated 结构体json导出的问题

### ISSUE THREAD

**Issue by daaoling** [davyxu/tabtoy#5]
![tabtoy issue](https://cloud.githubusercontent.com/assets/11972308/19101547/ce088044-8afb-11e6-8a26-ffdbb437655b.png)

**Comment by daaoling** [comment]
看了一下例子，好像没有支持结构体数组，可以在下一个版本支持吗？

**Comment by davyxu** [comment]
https://github.com/davyxu/tabtoy/blob/master/exportorv2/sample/Sample.xlsx
这里的StrStruct就是结构体数组
结构体数组要求每个element在一个独立的单元格， 而不是你的合并在一个单元格
