### ISSUE TITLE
是否可以导出二进制的protobuf文件？

### ISSUE THREAD

**Issue by kennir** [davyxu/tabtoy#51]
是否可以导出二进制的protobuf文件？

**Comment by davyxu** [comment]
不能

**Comment by kennir** [comment]
谢谢回复，请教一下， 不导出二进制的pb格式是基于什么样的考虑？ 二进制的pb格式读取和容量应该都优于text格式的pb

谢谢

**Comment by davyxu** [comment]
pb不支持动态字段, 即便我能导出, 你没有proto怎么读?

**Comment by kennir** [comment]
@davyxu  谢谢解释
