### ISSUE TITLE
导出go代码时会报错，看了一下，是没有生成包名

### ISSUE THREAD

**Issue by buptheidong** [davyxu/tabtoy#52]
1:      // Generated by github.com/davyxu/tabtoy
2:      // DO NOT EDIT!!
3:      // Version: 3.0.0
4:      package
5:
6:      type TableEnumValue struct {
7:              Name  string
8:              Index int32
9:      }

如上所示，包名是空的，是我打开方式不对么。

**Comment by davyxu** [comment]
-package 指定包名

**Comment by buptheidong** [comment]
ok，导出来了，多谢！
