### ISSUE TITLE
提个需求

### ISSUE THREAD

**Issue by buptheidong** [davyxu/tabtoy#53]
能不能在导出数据的时候加个导出方式，按照每个数据表的表名，导出对应的json文件，有几张数据表就导出几个json文件，用参数控制

**Comment by davyxu** [comment]
这是你自己用shell应该做的事情, 拆成几个shell导出

**Comment by buptheidong** [comment]
好吧，那我就拆shell吧

**Comment by davyxu** [comment]
最新的源码已经支持json/lua/binary按表导出, 有尝鲜需求可以自行编译二进制跑下
