### ISSUE TITLE
KV表的类型表要怎么填写？

### ISSUE THREAD

**Issue by buptheidong** [davyxu/tabtoy#54]
目前尝试了各种写法也导不出来。。文档里也没有说明

**Comment by davyxu** [comment]
https://github.com/davyxu/tabtoy#kv%E8%A1%A8

https://github.com/davyxu/tabtoy/tree/master/v3/example/xlsx

看KV表格式, 导不出来, 复述中也不说明

**Comment by buptheidong** [comment]
格式看了，找到问题了，是KV表在Index里的模式要填“键值表”
而文档中写的是“数据表”
