### ISSUE TITLE
lua枚举生成有问题

### ISSUE THREAD

**Issue by HiWill** [davyxu/tabtoy#56]
ActorType = {
		[0] = "Leader",
		[2] = "Pig",
		Monkey = 1,
		Hammer = 3,
	},

**Comment by davyxu** [comment]
问题是什么?  期望是什么?

**Comment by HiWill** [comment]
应该生成这样才对吧：
ActorType = {
Leader =0,
Monkey = 1,
Pig = 2,
Hammer = 3,
},

**Comment by HiWill** [comment]
> 问题是什么? 期望是什么?
期望生成：
ActorType = {
Leader =0,
Monkey = 1,
Pig = 2,
Hammer = 3,
},
目前生成：
ActorType = {
[0] = "Leader",
[2] = "Pig",
Monkey = 1,
Hammer = 3,
},
生成格式不正确

**Comment by davyxu** [comment]
这不是bug, 特性里写的有特殊映射方式

LuaValueMapperString:true
LuaStringMapperValue:true
LuaValueMapperString:true
LuaStringMapperValue:true

**Comment by HiWill** [comment]
> 这不是bug, 特性里写的有特殊映射方式
> 
> LuaValueMapperString:true
> LuaStringMapperValue:true
> LuaValueMapperString:true
> LuaStringMapperValue:true

好的，不好意思没仔细看说明！
