### ISSUE TITLE
可否指定外键对应的对象类型

### ISSUE THREAD

**Issue by yanjingzhaisun** [davyxu/tabtoy#57]
RT
目前的一个需求，是技能的效果可能会对应不同的对象类型。（例如有 DOTSkillEffectClass, HealSkillEffectClass等等），是否可以通过表格类型直接通过键值查询对应的对象类型？
还是推荐通过枚举类型，在导入之后的代码里面再手动连接？
（例如枚举类型 DOTSkillEffect时则读取 DOTSkillEffectClass，HealSkillEffect时则读取HealSkillEffectClass）

**Comment by davyxu** [comment]
后者.

表格数据导入后和逻辑层之间, 还需要有一层数据二次加工封装层, 主要是建立辅助索引, 例如:  经验到等级, 等级到经验的helper函数等

导表工具只提供最简单的数据导出加工合并功能, 对于使用者来说, 无需关心来源数据的格式(xlsx/csv等), 也无需过多关注数据如何加载(提供各种语言的胶水代码)

**Comment by yanjingzhaisun** [comment]
> 后者.
> 
> 表格数据导入后和逻辑层之间, 还需要有一层数据二次加工封装层, 主要是建立辅助索引, 例如: 经验到等级, 等级到经验的helper函数等
> 
> 导表工具只提供最简单的数据导出加工合并功能, 对于使用者来说, 无需关心来源数据的格式(xlsx/csv等), 也无需过多关注数据如何加载(提供各种语言的胶水代码)
感谢！
