### ISSUE TITLE
空的数组域被默认填入了0

### ISSUE THREAD

**Issue by yanjingzhaisun** [davyxu/tabtoy#58]
![批注 2020-07-29 105418](https://user-images.githubusercontent.com/6327230/88816102-0bb00b00-d18a-11ea-91f4-c3d8aa9ad06e.png)
![批注 2020-07-29 105514](https://user-images.githubusercontent.com/6327230/88816104-0c48a180-d18a-11ea-8a09-487644a2bd52.png)
![批注 2020-07-29 105355](https://user-images.githubusercontent.com/6327230/88816108-0c48a180-d18a-11ea-9da5-a2c7a3b08498.png)

如果是空的域，默认之前一直以为应该是是空list？

**Comment by davyxu** [comment]
图看不了,  空白单元格的逻辑是这样的:
1. 如果是1列的数组, 空白时, 默认输出空白数组
2. 如果把数组拆成多列, 那么默认值填充数组默认值, 数值的默认值为0

**Comment by davyxu** [comment]
已发现问题, 需要时间修复

**Comment by yanjingzhaisun** [comment]
> 已发现问题, 需要时间修复

使用 3.0.1 版本生成，问题依然存在。
数据xlsx:
![data](https://tva2.sinaimg.cn/large/69cf1444gy1ghb2foxdk1j212i01at8o.jpg)

Json（枚举数组为空，但是int数组仍然被默认添加了0）
![json](https://tva4.sinaimg.cn/large/69cf1444gy1ghb2fpd8yqj21cv00lq2w.jpg)

Binary（枚举数组和 int 数组都被添加了数值0）
![binary](https://tvax3.sinaimg.cn/large/69cf1444gy1ghb2foh19qj20pv0akgm9.jpg)

**Comment by davyxu** [comment]
方便做一个最小重现的demo么? 带表格和导出shell, 可以直接丢百度云给我个链接, 我来测试下

**Comment by yanjingzhaisun** [comment]
> 方便做一个最小重现的demo么? 带表格和导出shell, 可以直接丢百度云给我个链接, 我来测试下

好的。
链接：https://pan.baidu.com/s/1REHoU3E7WdbV1ErAsX3Trw 
提取码：s56g

连接为xlsx内容、json生成文件和Unity Debug 截图（C# Binary）

**Comment by davyxu** [comment]
抱歉, 版本build上有一些问题, 已经重新更新二进制下载, 请重新下载

**Comment by yanjingzhaisun** [comment]
> 抱歉, 版本build上有一些问题, 已经重新更新二进制下载, 请重新下载

感谢，测试后没有问题了！
