### ISSUE TITLE
关于类型表和数据表的设计

### ISSUE THREAD

**Issue by donneyT** [davyxu/tabtoy#59]
v2版本之前 都是表头和数据放在一起的
v3版本 类型表和数据表分离
想知道这么设计的好处是什么 
感觉策划用起来 不是很直观  可以麻烦告我这么设计的意义吗？

**Comment by davyxu** [comment]
1. Type.xlsx可以根据需要拆分成多文件, 所以无所谓膨胀.  
2. V3里任何类型的表都可以无限拆分, 这是V2达不到的
3. 因为表可以拆分, 所以V2里类型在不同表里写起来就会重复和歧义, 所以才决定把类型独立出来
4. V2每个表里都可以定义类型, 导致经常找不到类型定义在哪个表里. 也有类型先后定义的问题
5. 至于为啥要拆分多个表, 主要是为了方便多人协作避免表格冲突, 同时分类也比较清晰

**Comment by donneyT** [comment]
感谢回复
我是一个做游戏研发
协同合作 和 拆表 表示真的很少用到  
自定义类型到是有必要
我的建议是： 
    1.只把 自定义类型 做成一个表 （来解决类型定义先后 类型找不到的问题）
    2.导出字段限制 比如 client 和 server 某字段是否导出 这个是要的
    3.表冲突的问题 也没什么好的建议 一般个人负责个人的模块 也不会冲突
我个人感觉还是V2的设计好一些  V3目前好像不支持c++
以上只是个人体会  我还是会优先使用v2

**Comment by tenvick** [comment]
楼主的建议很好，作者应该给大家提供更多的选择而不是强行开表头和内容。

**Comment by davyxu** [comment]
喜欢V2就用V2, 还是无法阻挡自己的习惯, 可以自己写下嘛
