### ISSUE TITLE
给出的例子表格无法输出

### ISSUE THREAD

**Issue by lemonkiller** [davyxu/tabtoy#6]
tabtoy --mode=exportorv2 --json_out=.\config.json Sample.xlsx
[INFO] exportorv2 2016/11/17 10:36:51 ==========Run: Collect Type Info==========
[INFO] exportorv2 2016/11/17 10:36:51 Sample.xlsx
[ERROR] exportorv2 2016/11/17 10:36:51 TypeSheet: Field type not found, 'ActorType'

**Comment by davyxu** [comment]
请参考这个批处理写法
github.com\davyxu\tabtoy\exportorv2\sample\Export.bat

Sample表的内容是在Globals表里定义的, 你单独导出Sample表肯定会报错

如果你不想有很多表, 就把类型信息合并过去
