### ISSUE TITLE
当前版本不支持Map类型？

### ISSUE THREAD

**Issue by ly07** [davyxu/tabtoy#60]
你好：
在文档和示例中找了很久，没找到关于Map这种键值对数据类型的使用,不知道是不支持还是我没找到
另外我在V2的文档上上看到有支持【结构体】，我试了几次发现都会报错，不知道是我配置的方式不对，还是现在V3已经不支持了。求指教，谢谢

**Comment by davyxu** [comment]
看下例子，里面有
v3没写的功能就是不支持

**Comment by ly07** [comment]
V3版本 不支持Map这种键值对的数据类型，也不支持自定义的结构体？

**Comment by davyxu** [comment]
仔细看下例子

**Comment by ly07** [comment]
你好，请教最后一个问题，键值表也就是KV表的主要功能是什么？

**Comment by davyxu** [comment]
键值对配置，看文档和例子

**Comment by ly07** [comment]
我问了你半天，你一个问题也没回答，文档我看了，看完之后有这个几个疑问所以才想你请教，结果问了等于白问。哪怕你告诉我不支持或者支持我问的那两个功能都行。另外我要是能在文档中找到相应的说明我还用问你？这个工具我不是写不出来，我写出来了一个Python的,但是我发现你的这个更强大,那你当老师去请教！我知道你忙，大家都是从苦哈哈的底层做起来的，难道你现在出了书了，有点名气了就把别人都当废物么？！

**Comment by davyxu** [comment]
看你抱怨了半天, 还是没列出你不懂的东西. 请你仔细看下我回复你的答案,我认为是回答到位的. 至于你懂不懂, 能不能解决你的问题. 我不清楚
V3支持的, 都在文档里, 没写的, 肯定不支持
1. 结构体不支持
2. Map键值对, 我猜你要问的应该是如何建索引, 在https://github.com/davyxu/tabtoy, 这里, 按Ctrl+F, 弹出来搜索框里输入"为字段建立索引", 按回车

还有, 开源免费的东西, 都是为大家提供方便, 作者没有义务教会你. 请就事论事, 讨论表格的事情就好, 扯作者本人的经历毫无意义, 也会让作者感觉很不舒服
抱歉现在才回, 之前手机看的消息, 才切到电脑
