### ISSUE TITLE
v3: 请问支持自定义类型作为另一个自定义类型的字段类型吗？

### ISSUE THREAD

**Issue by hesansi** [davyxu/tabtoy#62]
举例：
一个自定义类型：Position，含有两个字段 x 和 y。
另一个自定义类型：NPCData，使用 Position 作为字段类型。
请问支持这种配置吗？

**Comment by davyxu** [comment]
不支持

**Comment by hesansi** [comment]
> 不支持

感谢答复！
那就把这个作为建议，望采纳

**Comment by davyxu** [comment]
v2有，v3取消是因为这种东西对配置不友好，结构复杂，以及造成无限极嵌套

**Comment by davyxu** [comment]
你可以用一个int[]，把数值切分后，读取表格转换为你的格式

**Comment by hesansi** [comment]
> 你可以用一个int[]，把数值切分后，读取表格转换为你的格式

感谢答复，了解了
