### ISSUE TITLE
windows运行报错：TableError.UnknownInputFileExtension 未知的输入文件扩展名 | index

### ISSUE THREAD

**Issue by hesansi** [davyxu/tabtoy#63]
命令：
tabtoy.exe -mode=v3 -index=index.xlsx -package=TableSpace -csharp_out=table_gen.cs -binary_out=table_gen.bin
Loading Index file: 'index'...
报错 log：
TableError.UnknownInputFileExtension 未知的输入文件扩展名 | index

**Comment by hesansi** [comment]
同样的表格，mac下运行能成功导出

**Comment by hesansi** [comment]
找到原因了，上面用的是 powershell ，换成 cmd 后成功导出了

**Comment by cCaesarr** [comment]
powershell命令里，路径要加双引号

**Comment by davyxu** [comment]
开源项目都是以Linux Bash为标准设计的, 不会兼容power shell,  Windows下运行请用git bash命令行
