### ISSUE TITLE
请问支持double类型吗？ 表里配了无法识别

### ISSUE THREAD

**Issue by cCaesarr** [davyxu/tabtoy#64]
菜鸟一枚
因为项目有大数值计算，float精度不够会引起误差。
配了下double，提示  unknown type:double

请问支持double类型吗？
支持的话需要在哪里添加类型呢？
谢谢！

**Comment by cCaesarr** [comment]
是导出c#遇到的

**Comment by davyxu** [comment]
看能自己编译么, 不方便我可以发你一个编译好的版本链接

**Comment by cCaesarr** [comment]
谢谢，我自己可以编
