### ISSUE TITLE
Issue 58 的问题似乎还是存在

### ISSUE THREAD

**Issue by aenerv7** [davyxu/tabtoy#65]
#58 里的问题似乎还是存在，我这边用 3.0.1 的 exe 在 Windows 上生成了一下发现仍然有这个问题：

自定义的类型：
<img width="1190" alt="Snipaste_20200831_160320" src="https://user-images.githubusercontent.com/4949197/91697607-fc1a4c80-eba3-11ea-850d-25b8e82e6c71.png">

数据表里的数据：
<img width="149" alt="Snipaste_20200831_160418" src="https://user-images.githubusercontent.com/4949197/91697642-0ccac280-eba4-11ea-9954-d9e7ede7fb5a.png">

json 的输出数据
<img width="229" alt="Snipaste_20200831_160504" src="https://user-images.githubusercontent.com/4949197/91697691-1d7b3880-eba4-11ea-9c38-fbfe07905fa0.png">

调试时断点显示的数据
<img width="696" alt="Snipaste_20200831_160249" src="https://user-images.githubusercontent.com/4949197/91698036-ab572380-eba4-11ea-8bc1-fde043f66aee.png">

**Comment by davyxu** [comment]
v2版本不会再调整

**Comment by davyxu** [comment]
单元格本来就是空的, 有什么问题?

**Comment by aenerv7** [comment]
空的单元格不是应该没有数据嘛？json 输出的是没有数据，但是在 C# 中运行时里面是由一条数据的...我这边是不是更新成 v3 的写法

**Comment by davyxu** [comment]
v2的这个问题有历史原因, 如果是新项目, 这边建议直接用v3, 老项目的话, 读取数据后自己处理下就是了

**Comment by aenerv7** [comment]
好的明白了，我这边先特殊处理一下，以后直接用 V3 版本了
