### ISSUE TITLE
kv表的tagaction不生效

### ISSUE THREAD

**Issue by greatwing** [davyxu/tabtoy#70]
// 将KV表的Tags转换过去
if tags != nil && tags.Value != "" {
    tagsType := kvtab.HeaderByName("标记")
    tf.Tags = strings.Split(tags.Value, tagsType.TypeInfo.ArraySplitter)
}

调试看到tags.Value是空字符串，tag的值保存在tags.ValueList
如果改成tf.Tags = tags.ValueList，kv表的tagaction才能生效

**Comment by davyxu** [comment]
使用哪个tagaction?

**Comment by greatwing** [comment]
> 使用哪个tagaction?

nogenfield_json

**Comment by davyxu** [comment]
指定字段不导出只影响Type表里的字段, KV表的行虽然最后要转为字段,但是并没有类型表描述, 自然无法用tag标记
建议拆分客户端服务器的表, 独立导出较为安全

**Comment by greatwing** [comment]
> 指定字段不导出只影响Type表里的字段, KV表的行虽然最后要转为字段,但是并没有类型表描述, 自然无法用tag标记
> 建议拆分客户端服务器的表, 独立导出较为安全

好的，多谢
