### ISSUE TITLE
拆列方面的疑问

### ISSUE THREAD

**Issue by shelllee** [davyxu/tabtoy#71]
- 版本

    `v3`

- 代码

    ``` C#
    List<int> column;
    ```

- 拆列方式

    | column | column | column | column | column | column | column | column | column |
    | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
    | 1 | 1 | 1 | 1 | 1 | 2 |  |  |  |

- 期待方式

    | column | column | column |
    | :-: | :-: | :-: |
    | 1,1,1 | 1,1,2 |  |

- 问题
    - 现在的模式，只能每列填写一个数，但数据量多的时候，列就太多了。是否可以支持上面这种数据，虽然每个里面填了3个数，但依然想把它合并到List<int>，而不是当字符串处理。
    - 对于空列，会输出默认数据，但有时候，还想用数据的量，判定有效数据有几个，这也会产生问题。所以有没有可以指定某些单元格不参与合并的方式？比如写null？
    - 或者有没有一些基础的复合数据的支持，比如vector3之类的？或者支持指定序列化json的方式？

**Comment by davyxu** [comment]
1. 一列写很复杂的数据格式本来就不合理
2. 类似坐标这种要写在一起的, 可以用数组切割, 进到代码中转换为目标类型
3. 空列默认填充默认值, 保证与列的数量一致, 如果觉得很麻烦, 可以加载后手动处理下过滤默认值(P.S.不要用默认值做逻辑, 这是非常不好的习惯)
4. 不支持复杂数据格式, 有这种需求要放表里, 本身就是表设计有问题

**Comment by shelllee** [comment]
> 1. 一列写很复杂的数据格式本来就不合理
> 2. 类似坐标这种要写在一起的, 可以用数组切割, 进到代码中转换为目标类型
> 3. 空列默认填充默认值, 保证与列的数量一致, 如果觉得很麻烦, 可以加载后手动处理下过滤默认值(P.S.不要用默认值做逻辑, 这是非常不好的习惯)
> 4. 不支持复杂数据格式, 有这种需求要放表里, 本身就是表设计有问题

对于回答中的第2条，我是想把xyz写一块，但拆列好像不支持，列表中的“期待方式”导出的话，只能当作list<string>进行配置，而不能当作list<int>

还是说有二级拆分符我没注意到的？

**Comment by davyxu** [comment]
就是当成list是最好的, table数据读取后, 还要把table数据格式转换为你内存结构啊

**Comment by shelllee** [comment]
- 想按这种方式拆列（虽然3个写一组，但整体这几列还是合并为同一个`list<int>`）

    | column | column | column |
    | :-: | :-: | :-: |
    | 1,1,1 | 1,1,2 |  |

- 但现在必须拆9列才行，因为上面那种写法，会当`list<string>`处理，是设计如此么

    | column | column | column | column | column | column | column | column | column |
    | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
    | 1 | 1 | 1 | 1 | 1 | 2 |  |  |  |

**Comment by shelllee** [comment]
然后第二点疑问，虽然vector3这种数据结构可能有嵌套数据的嫌疑（嵌套数据主要是语言不支持的数据类型？），但比如`list<list<int>>`这种完全的基础类型的组合，可以支持不

**Comment by davyxu** [comment]
要不要里面给你嵌一个浏览器? 嵌一个手机?
数据格式这么复杂, 就不要考虑用表存了

**Comment by shelllee** [comment]
哈哈，据说有那种可以直接做键值关联跟预览的，不过是基于浏览器的
