### ISSUE TITLE
tag_action能否支持一下lua

### ISSUE THREAD

**Issue by buptheidong** [davyxu/tabtoy#73]
我们客户端的数据是lua格式，需求能不导出服务器数据

**Comment by iaimstar** [comment]
我们也有这个需求呢

**Comment by davyxu** [comment]
https://github.com/davyxu/tabtoy/commit/abcd817558973d7b9869187bf470d86f8ca9f257
PR里有提过, 只是发布的版本还不包含, 等整合其他特性后再发布
如果急可以自行编译

**Comment by buptheidong** [comment]
好的，收到
