### ISSUE TITLE
tag_action的一些问题

### ISSUE THREAD

**Issue by buptheidong** [davyxu/tabtoy#74]
nogentable不生效
nogenfield_json在按表导出的模式下，不生效
![image](https://user-images.githubusercontent.com/11538229/102593384-c350b400-414f-11eb-8f28-4a4de1aab54c.png)
这是Index表，隐藏了类型表

![image](https://user-images.githubusercontent.com/11538229/102593484-e713fa00-414f-11eb-8cc9-867b61b445c5.png)
这是按表导出模式下的命令，两个action都不生效

![image](https://user-images.githubusercontent.com/11538229/102593557-fdba5100-414f-11eb-89af-06abf2f56f72.png)
这是整体导出下的命令，nogentable不生效

**Comment by davyxu** [comment]
为什么Client后有^    ?

**Comment by buptheidong** [comment]
windows批处理会把|解释为管道符，直接执行会崩，所以加上^进行转义

**Comment by davyxu** [comment]
你给的东西没法查
1. 自己下载源码自己跟踪问题
2. 表发出来我来查

**Comment by buptheidong** [comment]
[Index.xlsx](https://github.com/davyxu/tabtoy/files/5714650/Index.xlsx)
[02_01_Item.xlsx](https://github.com/davyxu/tabtoy/files/5714655/02_01_Item.xlsx)
[09_03_Navigation.xlsx](https://github.com/davyxu/tabtoy/files/5714658/09_03_Navigation.xlsx)
[03_03_Story.xlsx](https://github.com/davyxu/tabtoy/files/5714659/03_03_Story.xlsx)
[Type_Story.xlsx](https://github.com/davyxu/tabtoy/files/5714661/Type_Story.xlsx)
[Type_Navigation.xlsx](https://github.com/davyxu/tabtoy/files/5714662/Type_Navigation.xlsx)
[Type_Item.xlsx](https://github.com/davyxu/tabtoy/files/5714663/Type_Item.xlsx)

我发了个最小验证集合，Story表可以验证nogenfield_json，Navigation表可以验证nogentable

**Comment by davyxu** [comment]
https://github.com/davyxu/tabtoy#action%E7%B1%BB%E5%9E%8B
烦请仔细阅读说明,  导出类型和忽略类型对应好
