### ISSUE TITLE
还是tag_action的问题

### ISSUE THREAD

**Issue by buptheidong** [davyxu/tabtoy#75]
之前的issue被关了，只能新开了

我之前的issue里发的例子是哪配的不对么，Navigation配的Client，不导出，导出参数也是配的Client，可实际还是被导出来了呀
还有story表里配成了Client的字段，也都被导出来了呀

**Comment by buptheidong** [comment]
补充一下
分表导出命令
tabtoy.exe -mode=v3 -usecache=true -index=Index.xlsx -json_dir=json --tag_action=nogentable:Client^|nogenfield_json:Client

整表导出命令
tabtoy.exe -mode=v3 -index=Index.xlsx -json_out=json/data.json --tag_action=nogentable:Client^|nogenfield_json:Client

**Comment by buptheidong** [comment]
分表导出的问题找到问题了，是应该用nogenfield_jsondir

nogentable的问题也找到了，是文档中的关键字是“nogentable”，而代码里是“nogentab”，改成nogentab后，导出正常

**Comment by davyxu** [comment]
P.S. issue可以重开

**Comment by hupengfei24** [comment]
在windows系统下，shell命令下“|”符号会和tar_action冲突，会识别“\”后面的字符串是shell命令，直接报错，建议改为"*"或其他符合，例如
“-tag_action=nogenfield_csrender:render|nogenfield_cslogic:logic \” 改为
”-tag_action=nogenfield_csrender:render*nogenfield_cslogic:logic \“。然后代码里面tagaction.go里分隔符改为"*"
for _, as := range strings.Split(script, "*") {

**Comment by dxgzg** [comment]
谢谢，找到了答案，nogenfield_jsondir
