### ISSUE TITLE
v2版本导出c#，都包含Globals.xlsx, 会导致生成多份相同的Globals里面的方法冲突

### ISSUE THREAD

**Issue by xieliujian** [davyxu/tabtoy#79]
命令行如下 ：
`    cmd = "tabtoy.exe "
    if is_mac_plat:
        cmd = "./tabtoy "

    cmd += "--mode=v2 "
    cmd += "--csharp_out=" + dstdir + filenoext + ".cs "
    cmd += "--binary_out=" + dstbindir + filenoext.lower() + ".bytes "
    cmd += "--combinename=" + filenoext + "Cfg "
    cmd += "Globals.xlsx "
    cmd += filenoext + ".xlsx"`

2个Excel都用到了Globals.xlsx里面的定义，这样导出会导致Global里面的数据类型被导出2次。代码冲突。

**Comment by davyxu** [comment]
为啥要这么设计? 隔离为两个文件夹不好么?
