### ISSUE TITLE
数据文件的某些行在导出时会丢失

### ISSUE THREAD

**Issue by buptheidong** [davyxu/tabtoy#80]
02_03_Loot_Unit.xlsx的前46行可以正常导出，但是从47行开始就都没有被导出了
此时，如果打开excel文件，保存一下，就可以正常导出所有数据

文件如下：
[02_03_Loot_Unit.xlsx](https://github.com/davyxu/tabtoy/files/5855443/02_03_Loot_Unit.xlsx)
[Type_Loot_Unit.xlsx](https://github.com/davyxu/tabtoy/files/5855447/Type_Loot_Unit.xlsx)

shell命令如下：
tabtoy.exe -mode=v3 -usecache=true -index=Index.xlsx -json_dir=json --tag_action=nogentab:Client^|nogenfield_jsondir:Client

**Comment by davyxu** [comment]
index文件最好都提供下
