### ISSUE TITLE
V2 版本有空行时未报 Warning

### ISSUE THREAD

**Issue by aenerv7** [davyxu/tabtoy#82]
可以看到下图的表格中有大段空行

![image](https://user-images.githubusercontent.com/4949197/108582669-ab73f700-736f-11eb-9c59-ea31bdd7282b.png)

但执行导出时却未显示空行 Warning

![image](https://user-images.githubusercontent.com/4949197/108582696-ce9ea680-736f-11eb-87c0-dd4599503def.png)

**Comment by davyxu** [comment]
v2已经不再维护了

**Comment by aenerv7** [comment]
好吧，那请问可以告知一下这个功能的实现大概在哪一块吗？虽然不是很熟悉 Go，但既然如此准备自己试着改一下，谢谢！

**Comment by davyxu** [comment]
sheet_data.go
