### ISSUE TITLE
批量转换的时候出现 the system cannot find the file specified的错误，提示文件

### ISSUE THREAD

**Issue by yingnierxiao** [davyxu/tabtoy#83]
![image](https://user-images.githubusercontent.com/3435706/108706834-27299b80-754a-11eb-8d2b-a60e8a3fba73.png)
随机出现的

**Comment by davyxu** [comment]
不是工具的问题, 是你磁盘坏了

**Comment by yingnierxiao** [comment]
又不太像 几个人都是一样问题

**Comment by davyxu** [comment]
自己检查你的项目问题和tabtoy无关
