### ISSUE TITLE
HELP，C# binary读取丢失部分字段

### ISSUE THREAD

**Issue by Reekin** [davyxu/tabtoy#84]
测试表格如下：

![image](https://user-images.githubusercontent.com/29672213/113407496-fad22c00-93df-11eb-80db-1eb4af1a7c07.png)

![image](https://user-images.githubusercontent.com/29672213/113407451-e7bf5c00-93df-11eb-9505-fda1141ca5fa.png)

断点table_gen的反序列化过程发现读取iconName、maxOverlapNum、description、consumable时mamaSaidTagNameShouldBeLong变量都没有命中对应的case，被直接跳过了

换成了最新发布的exe也还是一样

**Comment by davyxu** [comment]
好歹给一些测试文件吧, 导出shell啥都没有, 鬼知道你是怎么导的

**Comment by Reekin** [comment]
> 好歹给一些测试文件吧, 导出shell啥都没有, 鬼知道你是怎么导的

不好意思，重启Unity之后发现莫名其妙好了，可能是Unity没有刷新脚本资源导致的问题
