### ISSUE TITLE
v3/example/xlsx/导出csharp二进制数据报错: 创建索引时发现重复值

### ISSUE THREAD

**Issue by wangzy88** [davyxu/tabtoy#86]
表没改动过, 感觉数值也没问题, 但是导出会报错

![image](https://user-images.githubusercontent.com/4112268/120634822-4798b880-c49e-11eb-87e1-e3aa806dcd96.png)

zhiyuan@DESKTOP-HNUCQPV MINGW64 /e/Desktop/tabtoy-master/v3/example/xlsx
$ ./tabtoy.exe -mode=v3 -index=Index.xlsx -package=main -csharp_out=table_gen.cs -binary_out=table_gen.bin
Loading Index file: 'Index.xlsx'...
Loading tables...
   (TypeDefine) Type.xlsx
   (ExampleData) Data.xlsx
   (ExampleData) Data2.xlsx
   (ExtendData) Extend.xlsx
   (ExampleKV) KV.xlsx
   (ExampleKV) KV2.xlsx
Checking types...
Merge key-value tables...
Merge data tables...
TableError.DuplicateValueInMakingIndex 创建索引时发现重复值 | '' @Data.xlsx|Sheet1(B3)

**Comment by davyxu** [comment]
不知道你下载的版本是什么, 有没有修改过文件

**Comment by wangzy88** [comment]
> 不知道你下载的版本是什么, 有没有修改过文件

Sorry给的信息不全,源码和release包下的都是最新版本 没有改过任何文件 就是把tabtoy.exe拷贝到v3/example/xlsx/下运行了下

**Comment by davyxu** [comment]
tabtoy最新编译出来的没有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月11日(周五) 下午3:39
收件人: ***@***.***&gt;;
抄送: "Davy ***@***.******@***.***&gt;;
主题: Re: [davyxu/tabtoy] v3/example/xlsx/导出csharp二进制数据报错: 创建索引时发现重复值 (#86)




  
不知道你下载的版本是什么, 有没有修改过文件
  
Sorry给的信息不全,源码和release包下的都是最新版本 没有改过任何文件 就是把tabtoy.exe拷贝到v3/example/xlsx/下运行了下

**Comment by wangzy88** [comment]
经过再次确认在/xlsx目录下运行确实存在问题 但是在/tutorial目录下运行没问题
补充相关信息: 
1 源码版本
![image](https://user-images.githubusercontent.com/4112268/122152204-84e44980-ce93-11eb-9298-46a793d5a5f7.png)

**Comment by davyxu** [comment]
我在win10下也试过， 没问题哈

**Comment by wangzy88** [comment]
确实最新编译的没问题 可以考虑更新下release包 我之前是直接用release包里的tabtoy.exe
感谢
