### ISSUE TITLE
float计算不准确导致单元格转换错误

### ISSUE THREAD

**Issue by hyhmm** [davyxu/tabtoy#9]
例：
**报错** 数据表: 单元格转换错误, type: 'int32' raw: '95040.000000000015'
其中95040.000000000015是有单元格的公式计算出来的=(1+0.1*AO38)*3600 * 24
_**AO38**_单元格的值为1。遇到这种能不能工具规避下

**Comment by davyxu** [comment]
能稍微给下这个数字的等效计算公式么? 我只能把95040.0000000000粘进去, 没有尾巴

**Comment by davyxu** [comment]
报错单元格的格式怎么设?我按你的方法没有重现bug

**Comment by hyhmm** [comment]
[http://pan.baidu.com/s/1bp7sjvD](url)  这个是出错的文件，麻烦看看

**Comment by davyxu** [comment]
你这个公式计算结果是一个浮点数, 而单元格默认只接收整形
导表工具报错是正确的
要解决这个问题, 将单元格公式取整就可以了=INT((1+0.1*C5)*3600*24)

这不是导表工具问题...
