### ISSUE TITLE
go导出文件报错

### ISSUE THREAD

**Issue by zylikedream** [davyxu/tabtoy#96]
v3 使用combinename选项时，go导出的模板有问题，导致生成的代码报错。
![image](https://user-images.githubusercontent.com/7788749/146335854-23d00d91-eeaa-4872-8b0c-9bd6b34fccbf.png)
![image](https://user-images.githubusercontent.com/7788749/146335977-7572dabd-6129-47e8-827b-91d68c6ae6c3.png)

**Comment by davyxu** [comment]
已经修复, 可以自己取下代码编译下tabtoy即可

**Comment by zylikedream** [comment]
感谢！！
