### ISSUE TITLE
请问表格中标记列的标记有没有解释?

### ISSUE THREAD

**Issue by laniidae** [davyxu/tabtoy#99]
例如示例中
Index.xlxs
![Snipaste_2022-03-27_18-51-13](https://user-images.githubusercontent.com/31888615/160279488-1699490b-97d6-4199-a78f-a8b779825d59.png)

KV.xlx
<img width="393" alt="Snipaste_2022-03-27_19-18-46" src="https://user-images.githubusercontent.com/31888615/160279493-3c7a814b-dc23-43f9-b3b5-c147dafe140f.png">

这是什么通用规则吗?

**Comment by davyxu** [comment]
自己定义功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月27日(周日) 晚上7:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [davyxu/tabtoy] 请问表格中标记列的标记有没有解释? (Issue #99)




 
例如示例中
 Index.xlxs
 
 
KV.xlx
 
 
这是什么通用规则吗?

**Comment by laniidae** [comment]
@davyxu 也就是说示例中的标记只是演示对吗? 好的谢谢
